# Generated by Django 5.2.8 on 2025-11-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_rename_location_userprofile_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefecture',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
