# Generated by Django 5.2.8 on 2025-12-02 10:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_message_image_message_video_alter_message_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_checked_likes',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_checked_matches',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.userprofile')),
            ],
            options={
                'unique_together': {('user', 'room')},
            },
        ),
    ]
