# Generated by Django 5.2.8 on 2025-12-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_userprofile_last_checked_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_checked_messages',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
