# Generated by Django 5.2.8 on 2025-12-03 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0011_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(default='recommended', max_length=20)),
                ('age_filter', models.CharField(default='any', max_length=10)),
                ('prefecture', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('income_min', models.IntegerField(blank=True, null=True)),
                ('income_max', models.IntegerField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_conditions', to='matching.userprofile')),
            ],
        ),
    ]
