# Generated by Django 5.2.8 on 2025-12-04 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0012_searchcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('body', models.TextField(blank=True, verbose_name='本文')),
                ('image', models.ImageField(blank=True, null=True, upload_to='board_images/', verbose_name='画像')),
                ('is_call_invite', models.BooleanField(default=False, verbose_name='通話相手を募集する')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_posts', to='matching.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
