# Generated by Django 5.2.8 on 2025-12-05 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0013_boardpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='purpose',
            field=models.CharField(blank=True, choices=[('friend', '友達作り'), ('love', '恋人探し'), ('both', '友達も恋人も両方'), ('hobby', '趣味友達'), ('talk', '暇つぶし・話し相手')], max_length=20, verbose_name='利用目的'),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='お名前')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('subject', models.CharField(max_length=200, verbose_name='件名')),
                ('body', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='matching.userprofile')),
            ],
        ),
    ]
